//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace AppLocator.DatabaseModel
{
    public partial class DatabaseEntities : ObjectContext
    {
        public const string ConnectionString = "name=DatabaseEntities";
        public const string ContainerName = "DatabaseEntities";
    
        #region Constructors
    
        public DatabaseEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public DatabaseEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public DatabaseEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<APIUrl> APIUrl
        {
            get { return _aPIUrl  ?? (_aPIUrl = CreateObjectSet<APIUrl>("APIUrl")); }
        }
        private ObjectSet<APIUrl> _aPIUrl;

        #endregion
    }
}
