SET DEFINE OFF;
Prompt drop TABLE AN_FRM_OBJ_SECTION;
ALTER TABLE AN_FRM_OBJ_SECTION
 DROP PRIMARY KEY CASCADE
/

DROP TABLE AN_FRM_OBJ_SECTION CASCADE CONSTRAINTS PURGE
/

Prompt Table AN_FRM_OBJ_SECTION;
--
-- AN_FRM_OBJ_SECTION  (Table) 
--
--  Dependencies: 
--   AN_FRM_OBJ_FORM (Table)
--
CREATE TABLE AN_FRM_OBJ_SECTION
(
  OBJECT_ID     INTEGER,
  PARENT        INTEGER                         NOT NULL,
  HEADER_TITLE  VARCHAR2(200 CHAR),
  FOOTER_TITLE  VARCHAR2(200 CHAR),
  ORDER_NO      INTEGER                         DEFAULT 0                     NOT NULL
)
/






-- 
-- Non Foreign Key Constraints for Table AN_FRM_OBJ_SECTION 
-- 
Prompt Non-Foreign Key Constraints on Table AN_FRM_OBJ_SECTION;
ALTER TABLE AN_FRM_OBJ_SECTION ADD (
  CONSTRAINT AN_FRM_OBJ_SECTION_PK
  PRIMARY KEY
  (OBJECT_ID)
  USING INDEX
)
/

ALTER TABLE AN_FRM_OBJ_SECTION ADD (
  CONSTRAINT AN_FRM_OBJ_SECTION_U01
  UNIQUE (OBJECT_ID, PARENT)
  USING INDEX
)
/


-- 
-- Foreign Key Constraints for Table AN_FRM_OBJ_SECTION 
-- 
Prompt Foreign Key Constraints on Table AN_FRM_OBJ_SECTION;
ALTER TABLE AN_FRM_OBJ_SECTION ADD (
  CONSTRAINT AN_FRM_OBJ_SECTION_R01 
  FOREIGN KEY (PARENT) 
  REFERENCES AN_FRM_OBJ_FORM (OBJECT_ID))
/
