SET DEFINE OFF;
Prompt drop TABLE AN_FRM_OBJ_FIELD;
ALTER TABLE AN_FRM_OBJ_FIELD
 DROP PRIMARY KEY CASCADE
/

DROP TABLE AN_FRM_OBJ_FIELD CASCADE CONSTRAINTS PURGE
/

Prompt Table AN_FRM_OBJ_FIELD;
--
-- AN_FRM_OBJ_FIELD  (Table) 
--
--  Dependencies: 
--   AN_FRM_CONS_FIELD_TYPE (Table)
--   AN_FRM_OBJ_FORM (Table)
--   AN_FRM_OBJ_SECTION (Table)
--
CREATE TABLE AN_FRM_OBJ_FIELD
(
  OBJECT_ID  INTEGER,
  PARENT     INTEGER                            NOT NULL,
  SUBFORM    INTEGER,
  LABEL      VARCHAR2(200 CHAR),
  TYPE       VARCHAR2(50 CHAR)                  NOT NULL,
  INLINE     CHAR(1 CHAR)                       DEFAULT 1                     NOT NULL,
  COMPACT    CHAR(1 CHAR)                       DEFAULT 1                     NOT NULL,
  ORDER_NO   INTEGER                            DEFAULT 0                     NOT NULL
)
/






-- 
-- Non Foreign Key Constraints for Table AN_FRM_OBJ_FIELD 
-- 
Prompt Non-Foreign Key Constraints on Table AN_FRM_OBJ_FIELD;
ALTER TABLE AN_FRM_OBJ_FIELD ADD (
  CONSTRAINT AN_FRM_OBJ_FIELD_PK
  PRIMARY KEY
  (OBJECT_ID)
  USING INDEX
)
/

ALTER TABLE AN_FRM_OBJ_FIELD ADD (
  CONSTRAINT AN_FRM_OBJ_FIELD_U01
  UNIQUE (OBJECT_ID, PARENT)
  USING INDEX
)
/


-- 
-- Foreign Key Constraints for Table AN_FRM_OBJ_FIELD 
-- 
Prompt Foreign Key Constraints on Table AN_FRM_OBJ_FIELD;
ALTER TABLE AN_FRM_OBJ_FIELD ADD (
  CONSTRAINT AN_FRM_OBJ_FIELD_R01 
  FOREIGN KEY (PARENT) 
  REFERENCES AN_FRM_OBJ_SECTION (OBJECT_ID))
/

ALTER TABLE AN_FRM_OBJ_FIELD ADD (
  CONSTRAINT AN_FRM_OBJ_FIELD_R02 
  FOREIGN KEY (SUBFORM) 
  REFERENCES AN_FRM_OBJ_FORM (OBJECT_ID))
/

ALTER TABLE AN_FRM_OBJ_FIELD ADD (
  CONSTRAINT AN_FRM_OBJ_FIELD_R03 
  FOREIGN KEY (TYPE) 
  REFERENCES AN_FRM_CONS_FIELD_TYPE (VALUE))
/
