SET DEFINE OFF;
Prompt drop TABLE AN_FRM_OBJ_FORM;
ALTER TABLE AN_FRM_OBJ_FORM
 DROP PRIMARY KEY CASCADE
/

DROP TABLE AN_FRM_OBJ_FORM CASCADE CONSTRAINTS PURGE
/

Prompt Table AN_FRM_OBJ_FORM;
--
-- AN_FRM_OBJ_FORM  (Table) 
--
CREATE TABLE AN_FRM_OBJ_FORM
(
  OBJECT_ID  INTEGER,
  TITLE      VARCHAR2(200 CHAR)
)
/




-- 
-- Non Foreign Key Constraints for Table AN_FRM_OBJ_FORM 
-- 
Prompt Non-Foreign Key Constraints on Table AN_FRM_OBJ_FORM;
ALTER TABLE AN_FRM_OBJ_FORM ADD (
  CONSTRAINT AN_FRM_OBJ_FORM_PK
  PRIMARY KEY
  (OBJECT_ID)
  USING INDEX
)
/
